apiVersion: v1
kind: Service
metadata:
  labels:
    app: tercen-stage
  name: tercen-stage-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5400
      protocol: TCP
  selector:
    app: tercen-stage