# ALL 0 # OFF 2000 # FINEST 300 # FINER 400 # FINE 500 # CONFIG 700 # INFO 800 # WARNING 900 # SEVERE 1000 # SHOUT 1200
# tercen.log.level: '400'
tercen.couchdb.address: couchdb

tercen.client.uri: http://tercen:5400
tercen.public.uri: http://172.17.0.1:5402
tercen.public.client.uri: http://172.17.0.1:5402
tercen.worker.public.ip: 172.17.0.1
tercen.worker.ip: tercen

#tercen.allow.untrusted.docker: 'false'
# accept any image name starting by tercen, ex. tercen/something
#tercen.trusted.docker:
#  - 'tercen'

tercen.worker.docker.operator.folder: /var/lib/tercen/data/operator/
#tercen.worker.docker.image: tercen/dartrusttidy:1.0.10
#tercen.worker.docker.network: host
tercen.worker.docker.remove.on.start: 'true'

DefaultProfiles:
- 2.api.profile
- 2.table.profile
- 2.cpuTime.profile
- 2.storage.profile
- 2.run.profile

# LDAP
#tercen.user.service: 'ldap'
#tercen.user.service.ldap.host: '127.0.0.1'
#tercen.user.service.ldap.protocol: ''
#tercen.user.service.ldap.port: '389'
## TLS
## tercen.user.service.ldap.protocol: 'ssl'
## tercen.user.service.ldap.port: '636'
#
#tercen.user.service.ldap.bind: 'dc=example,dc=org'