# ALL 0 # OFF 2000 # FINEST 300 # FINER 400 # FINE 500 # CONFIG 700 # INFO 800 # WARNING 900 # SEVERE 1000 # SHOUT 1200
# tercen.log.level: '400'
tercen.couchdb.address: couchdb

# will use all available cpu and memory
tercen.worker.proc.override: 'true'
tercen.worker.proc.override.isolates.cpu.ratio: '1.0'

# manually set available worker threads and memory
#tercen.worker.isolates: '4'
# set 7G of available memory
#tercen.worker.memory: '7096000000'

DefaultProfiles:
- 2.api.profile
- 2.table.profile
- 2.cpuTime.profile
- 2.storage.profile
- 2.run.profile

# LDAP
#tercen.user.service: 'ldap'
#tercen.user.service.ldap.host: '127.0.0.1'
#tercen.user.service.ldap.protocol: ''
#tercen.user.service.ldap.port: '389'
## TLS
## tercen.user.service.ldap.protocol: 'ssl'
## tercen.user.service.ldap.port: '636'
#
#tercen.user.service.ldap.bind: 'dc=example,dc=org'