configs:
  - domain: ''
    hosts:
      - 127.0.0.1
      - tercen
    config:
      tercen.auth.cookie.domain: 127.0.0.1
# ALL 0 # OFF 2000 # FINEST 300 # FINER 400 # FINE 500 # CONFIG 700 # INFO 800 # WARNING 900 # SEVERE 1000 # SHOUT 1200
tercen.log.level: '0'
tercen.couchdb.address: couchdb
tercen.couchdb.user: admin
tercen.couchdb.password: admin

tercen.client.uri: http://tercen:5400
tercen.worker.ip: tercen
tercen.worker.runtime.ip: runtime-docker

#tercen.docker.network: tercen
#tercen.client.uri: http://tercen:5400
#tercen.worker.public.ip: tercen
#tercen.worker.ip: tercen
#tercen.worker.webapp.ip: runtime
#tercen.public.uri: http://tercen:5400
#tercen.public.client.uri: http://tercen:5400

tercen.external.storage.enabled: 'true'
## external.storage path must the same on the host and in the container
#tercen.external.storage.read.path: '/var/lib/tercen/external/read'
#tercen.external.storage.write.path: '/var/lib/tercen/external/write'

#tercen.auth.method: 'saml'
#tercen.saml.request.issuer: https://my.tercen.com/_service/sso/auth/saml
#tercen.saml.idp.issuer: https://sts.windows.net/5b5c94c6-14cf-42da-85bc-4e08722b253b/
#tercen.saml.audience: https://my.tercen.com/_service/sso/auth/saml
#tercen.saml.binding.url: https://login.microsoftonline.com/5b5c94c6-14cf-42da-85bc-4e08722b253b/saml2
#tercen.saml.certificate.file: /etc/tercen/saml/cert.pem

# default true, accept any imag
#tercen.allow.untrusted.docker: 'false'

# accept any image name starting by tercen or my-trusted-docker-repo, ex. my-trusted-docker-repo/my-docker-image
#tercen.trusted.docker:
#  - 'tercen'
#  - 'my-trusted-docker-repo'

#tercen.r.operator.reinstall: 'true'

# will use all available cpu and memory
tercen.worker.proc.override: 'true'
tercen.worker.proc.override.isolates.cpu.ratio: '1.0'

# manually set available worker threads and memory
#tercen.worker.isolates: '4'
# set 7G of available memory
#tercen.worker.memory: '7096000000'

DefaultProfiles:
  - 2.api.profile
  - 2.table.profile
  - 2.cpuTime.profile
  - 2.storage.profile
  - 2.run.profile

# LDAP
#tercen.user.service: 'ldap'
#tercen.user.service.ldap.host: '127.0.0.1'
#tercen.user.service.ldap.protocol: ''
#tercen.user.service.ldap.port: '389'
## TLS
## tercen.user.service.ldap.protocol: 'ssl'
## tercen.user.service.ldap.port: '636'
#
#tercen.user.service.ldap.bind: 'dc=example,dc=org'