version: "3.2"
services:

  couchdb:
    image: couchdb:1.7.2
    env_file:
      - config/env/couchdb.env
    volumes:
      - couchdb-data:/usr/local/var/lib/couchdb
      - ./config/couchdb:/usr/local/etc/couchdb/local.d
    restart: always

  tercen:
    links:
      - couchdb
# see : https://hub.docker.com/r/tercen/tercen/tags?page=1&ordering=last_updated
# for specific version
    image: tercen/tercen:stage
    ports:
      - "5402:5400"
    env_file:
      - config/env/couchdb.env
    volumes:
      - tercen-data:/var/lib/tercen/data
      - ./config/tercen:/etc/tercen
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  runtime-r35:
    image: tercen/runtime-r35:3.5.3-0
    volumes:
      - tercen-data:/var/lib/tercen/data
    restart: always

  runtime-r40:
    image: tercen/runtime-r40:4.0.3-0
    volumes:
      - tercen-data:/var/lib/tercen/data
      - tercen-conda:/root/.local/share/r-miniconda
    restart: always

  tercen_studio:
    links:
      - tercen
    image: tercen/tercen_studio:4.0.3-6
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=tercen
    volumes:
      - tercen-studio-conda:/home/rstudio/.local/share/r-miniconda
      - tercen-studio-renv:/home/rstudio/.local/share/renv
      - tercen-studio-data:/home/rstudio/projects
      - ./config/tercen-studio/.Rprofile:/home/rstudio/.Rprofile
      - ./config/tercen-studio/examples:/home/rstudio/projects/examples
    # sharing gitconfig can be usefull
#      - ~/.gitconfig:/home/rstudio/.gitconfig
    restart: always

volumes:
  couchdb-data:
  tercen-data:
  tercen-conda:
  tercen-studio-data:
  tercen-studio-renv:
  tercen-studio-conda: