version: "3.9"

services:

  couchdb:
    image: ibmcom/couchdb3:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb3-data:/opt/couchdb/data
    restart: always

  tercen:
    image: tercen/tercen:0.6
#    image: tercen/tercen:latest
    ports:
      - "5402:5400"
    volumes:
      - tercen-data:/var/lib/tercen/data
      - ./config/tercen:/etc/tercen
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  runtime-r35:
    image: tercen/runtime-r35:3.5.3-5
    volumes:
      - tercen-data:/var/lib/tercen/data
    restart: always

  runtime-r40:
    image: tercen/runtime-r40:4.0.4-1
    volumes:
      - tercen-data:/var/lib/tercen/data
    restart: always

  tercen_studio:
    image: tercen/tercen_studio:4.0.4-0
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=tercen
    volumes:
      - tercen-studio-renv:/home/rstudio/.local/share/renv
      - tercen-studio-data:/home/rstudio/projects
      - ./config/tercen-studio/.Rprofile:/home/rstudio/.Rprofile
      - ./config/tercen-studio/examples:/home/rstudio/projects/examples
    restart: always

# docker network create tercen
# see in config file property
# tercen.docker.network: tercen
networks:
  default:
    external: true
    name: tercen

volumes:
  couchdb3-data:
  tercen-data:
  tercen-studio-data:
  tercen-studio-renv: