version: "3.9"

networks:
  tercen:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16

services:

  tercen_studio:
    networks:
      tercen:
        aliases:
          - tercen_studio
    image: tercen/tercen-studio-r40:4.0.4-7
    ports:
      - 8787:8787
    environment:
      - PASSWORD=tercen
    volumes:
      - var-run:/var/run
      - /var/lib/tercen/share:/var/lib/tercen/share
      - tercen-studio-renv:/home/rstudio/.local/share/renv
      - tercen-studio-data:/home/rstudio/projects
      - ./config/tercen-studio/.Rprofile:/home/rstudio/.Rprofile
      - ./config/tercen-studio/examples:/home/rstudio/projects/examples
# uncomment to share host ssh and git config with tercen-studio
#      - ~/.ssh:/home/rstudio/.ssh
#      - ~/.gitconfig:/home/rstudio/.gitconfig
    restart: always

volumes:
  couchdb3-data:
  tercen-data:
  tercen-studio-data:
  tercen-studio-renv:
  var-lib-docker:
  var-run:
  tmp: