version: "3.2"

networks:
  tercen:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16

services:

  couchdb:
    image: couchdb:1.7.2
    networks:
      tercen:
        aliases:
          - couchdb
    env_file:
      - config/env/couchdb.env
    volumes:
      - couchdb-data:/usr/local/var/lib/couchdb
      - ./config/couchdb:/usr/local/etc/couchdb/local.d
    restart: always

  tercen:
    networks:
      tercen:
        ipv4_address: 172.42.0.42
        aliases:
          - tercen
    image: tercen/tercen:0.5.89-7
    ports:
      - "5402:5400"
#    environment:
#      - tercen.r.operator.docker.reinstall=true
#      - TERCEN_R_OPERATOR_RUN_TEST=false
    env_file:
      - config/env/couchdb.env
    volumes:
      - tercen-data:/var/lib/tercen/data
      - ./config/tercen:/etc/tercen
      - ./run_user_1000:/var/run
    restart: always

  runtime-docker:
    privileged: true
#    image: docker:20.10.9-dind-alpine3.14
    image: docker:20.10.11-dind-rootless

    networks:
      tercen:
        aliases:
          - runtime-docker
    volumes:
#      - var-run:/var/run
      - ./run_user_1000:/run/user/1000
      - ./rootless_home:/home/rootless
      - var-lib-docker:/var/lib/docker
      - tercen-data:/var/lib/tercen/data
    restart: always

  runtime-r35:
    restart: always
    volumes:
      - ./run_user_1000:/var/run
    image: docker:20.10
    command: >
      sh -c "docker rm -f runtime-r35 || true &&
      docker run --rm --name runtime-r35
      --network host
      -v /var/lib/tercen/data:/var/lib/tercen/data
      tercen/runtime-r35:3.5.3-5"

  runtime-r40:
    restart: always
    volumes:
      - ./run_user_1000:/var/run
    image: docker:20.10
    command: >
      sh -c "docker rm -f runtime-r40 || true &&
      docker run --rm --name runtime-r40
      --network host
      -v /var/lib/tercen/data:/var/lib/tercen/data
      tercen/runtime-r40:4.0.4-1"

  tercen_studio:
    networks:
      tercen:
        aliases:
          - tercen_studio
    image: tercen/tercen_studio:4.0.4-0
    ports:
      - "8787:8787"
    environment:
      - FORCE_RECREATE=7
      - PASSWORD=tercen
    volumes:
      - tercen-studio-renv:/home/rstudio/.local/share/renv
      - tercen-studio-data:/home/rstudio/projects
      - ./config/tercen-studio/.Rprofile:/home/rstudio/.Rprofile
      - ./config/tercen-studio/examples:/home/rstudio/projects/examples
    # sharing gitconfig can be usefull
#      - ~/.gitconfig:/home/rstudio/.gitconfig
    restart: always

volumes:
  couchdb-data:
  tercen-data:
  tercen-studio-data:
  tercen-studio-renv:
  var-lib-docker:
  var-run:
  rootless-home: