version: "3.9"

networks:
  tercen:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16

services:

  couchdb:
    networks:
      tercen:
        aliases:
          - couchdb
    image: ibmcom/couchdb3:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb3-data:/opt/couchdb/data
    restart: always

  tercen:
    networks:
      tercen:
        ipv4_address: 172.42.0.42
        aliases:
          - tercen
    image: tercen/tercen:0.11
#    image: tercen/tercen:stage
    ports:
      - 5402:5400
    volumes:
      - /var/lib/tercen/external:/var/lib/tercen/external
      - tercen-data:/var/lib/tercen/data
      - ./config/tercen:/etc/tercen
      - var-run:/var/run
      - tmp:/tmp
    restart: always

  sarno:
    networks:
      tercen:
        aliases:
          - sarno
    image: tercen/sarno:0.2
#    image: tercen/sarno:stage
    volumes:
      - tercen-data:/var/lib/tercen/data
      - tmp:/tmp
    restart: always

  runtime-docker:
    privileged: true
    image: docker:24.0.6-dind-alpine3.18
#    image: docker:20.10.9-dind-alpine3.14
    networks:
      tercen:
        aliases:
          - runtime-docker
    volumes:
      - var-run:/var/run
      - var-lib-docker:/var/lib/docker
      - tercen-data:/var/lib/tercen/data
      - /var/lib/tercen/external:/var/lib/tercen/external
      - tmp:/tmp
    restart: always

  tercen_studio:
    networks:
      tercen:
        aliases:
          - tercen_studio
    image: tercen/tercen-studio-r40:4.0.4-7
    # image: tercen/tercen-studio-flowsuite:3.15-6
    ports:
      - 8787:8787
    environment:
      - PASSWORD=tercen
    volumes:
      - var-run:/var/run
      - /var/lib/tercen/share:/var/lib/tercen/share
      - tercen-studio-renv:/home/rstudio/.local/share/renv
      - tercen-studio-data:/home/rstudio/projects
      - ./config/tercen-studio/.Rprofile:/home/rstudio/.Rprofile
      - ./config/tercen-studio/examples:/home/rstudio/projects/examples
# uncomment to share host ssh and git config with tercen-studio
#      - ~/.ssh:/home/rstudio/.ssh
#      - ~/.gitconfig:/home/rstudio/.gitconfig
    restart: always

  code-server:
    image: tercen/tercen-code-py39:3.9.17-2
    container_name: code-server
    environment:
      - PUID=1001
      - PGID=1001
      - PASSWORD=tercen
      - SUDO_PASSWORD=tercen
    volumes:
      - code-server-data:/config
    networks:
      tercen:
        aliases:
          - code-server
    ports:
      - 8443:8443
    restart: unless-stopped

volumes:
  couchdb3-data:
  code-server-data:
  tercen-data:
  tercen-studio-data:
  tercen-studio-renv:
  var-lib-docker:
  var-run:
  tmp:
