; Tercen requires the Erlang query server (disabled by default in CouchDB 3.5+)
[native_query_servers]
enable_erlang_query_server = true

[couchdb]
single_node = true
uuid = cb3ef0e45fcf03039ce4f997d6c600f5

[chttpd]
bind_address = 0.0.0.0

[cluster]
n = 1

[admins]
admin = -pbkdf2:sha256-1a27728d83fda8141d4818f2ad04d1a3a1910b65b3fafbab7a26d961877ccf63,902bf1b99a457349bf002afa01e0161b,600000
