apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-job
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: create-job-role
rules:
  - apiGroups: [ "", "batch", "extensions" ]
    resources: [ "pods", "pods/log","jobs" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-job-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: create-job
    namespace: default
roleRef:
  kind: ClusterRole
  name: create-job-role
  apiGroup: rbac.authorization.k8s.io