# ALL 0 # OFF 2000 # FINEST 300 # FINER 400 # FINE 500 # CONFIG 700 # INFO 800 # WARNING 900 # SEVERE 1000 # SHOUT 1200
#tercen.log.level: '0'
tercen.log.level: '700'

tercen.allow.untrusted.git: 'false'

tercen.test.password: TestMe42!
tercen.admin.password: Crabs42!
tercen.worker.password: Crabs42!

tercen.auth.client.id.google: '653844972403-ve6tjq31861siedt2pqp1h6ilk5kgbvk.apps.googleusercontent.com'
tercen.auth.client.secret.google: 'dEPdZ8gXVPWotWctWRjFHXhi'

tercen.user.sign.up: 'true'
tercen.public.uri: https://stage.tercen.com
tercen.public.client.uri: https://stage.tercen.com
tercen.github.token: 0493846ce6e270d5da22e5474e167ebee1704dfc
tercen.smtp.username: info@tercen.com
tercen.smtp.password: Tercen42

tercen.couchdb.address: couchdb-stage
tercen.couchdb.user: admin
tercen.couchdb.password: admin
tercen.worker.isolates: "4"
tercen.ws.compression: "on"

tercen.stripe.tax.id: txr_1Gk71bJ8Q4DJdUwUSmjGvtha
tercen.stripe.customer.id.meta.data: stripeCustomerId_test
tercen.stripe.webhook.endpoint: stripe/RnyAQVwaDaXjGl9cP
tercen.stripe.public.key: pk_test_OnuOMsQHtrpQ3O8nBLtF7Z1100g0LW8aUz
tercen.stripe.key: sk_test_ygL3BiLvokJtxO1B0TWphBDy00q1B36i8t
tercen.stripe.test.key: sk_test_ygL3BiLvokJtxO1B0TWphBDy00q1B36i8t
tercen.stripe.public.test.key: pk_test_OnuOMsQHtrpQ3O8nBLtF7Z1100g0LW8aUz

Plans:
  - kind: Plan
    name: plan.1
    displayName: "Free"
    paymentProviderPlanId: ''
    descriptions:
      - "Unlimited public project"
      - "Unlimited private project"
      - "Unlimited team"
      - "10 GB of storage"
      - "10 hours cpu/month"
      - "1 hour training session"
      - "..."
    price: 0.0
  - kind: Plan
    name: plan.2
    displayName: "Standard"
    paymentProviderPlanId: plan_HIhdUd0ttaUqUq
    descriptions:
      - "All free features"
      - "400 GB of storage"
      - "40 hours cpu/month"
      - "3 hour training session"
      - "..."
    price: 20.0
  - kind: Plan
    name: plan.3
    displayName: "Pro"
    paymentProviderPlanId: plan_HIheHRFlvIbhZA
    descriptions:
      - "All free features"
      - "1 TB of storage"
      - "100 hours cpu/month"
      - "5 hour training session"
      - "..."
    price: 50.0