apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tercen-studio
  namespace: argocd
spec:
  destination:
    namespace: tercen-studio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/tercen/tercen_studio
    path: examples/k3d/manifest
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true