kind: Service
apiVersion: v1
metadata:
  name: tercen-service
spec:
  type: NodePort
  selector:
    app: tercen
  ports:
    - port: 5400
      nodePort: 30054
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tercen-deployment
  labels:
    app: tercen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tercen
  template:
    metadata:
      labels:
        app: tercen
    spec:
      restartPolicy: Always
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - tercen-worker
      volumes:
        - name: tercen-config
          configMap:
            name: tercen-config
#        - name: tercen-saml-cert
#          configMap:
#            name: tercen-saml-cert
        - name: tercen-tmp
          emptyDir: {}
        - name: var-run
          emptyDir: {}
        - name: tercen-data
          persistentVolumeClaim:
            claimName: tercen-data-pvc
        - name: tercen-renv
          persistentVolumeClaim:
            claimName: tercen-renv-pvc
        - name: tercen-operator
          persistentVolumeClaim:
            claimName: tercen-operator-pvc
        - name: var-lib-docker
          persistentVolumeClaim:
            claimName: tercen-var-lib-docker-pvc
      containers:
        - name: tercen
          image: tercen/tercen:0.11
          imagePullPolicy: Always
          ports:
            - containerPort: 5400
              name: tercen
          volumeMounts:
            - name: tercen-tmp
              mountPath: /tmp
              readOnly: false
            - name: tercen-config
              mountPath: /etc/tercen
#            - name: tercen-saml-cert
#              mountPath: /etc/tercen/saml
            - name: tercen-data
              mountPath: /var/lib/tercen/data
              readOnly: false
            - name: tercen-operator
              mountPath: /var/lib/tercen/data/operator
              readOnly: false
            - name: tercen-renv
              mountPath: /var/lib/tercen/data/renv/
              readOnly: false
            - name: var-run
              mountPath: /var/run/
        - name: sarno
          image: tercen/sarno:0.2.4
          imagePullPolicy: Always
          env:
            - name: k8s.force.reload
              value: "0"
            - name: RUST_BACKTRACE
              value: "1"
          volumeMounts:
            - name: tercen-data
              mountPath: /var/lib/tercen/data
              readOnly: false
            - name: tercen-tmp
              mountPath: /tmp
              readOnly: false
        - name: runtime-docker
          image: docker:20.10.9-dind-alpine3.14
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: var-run
              mountPath: /var/run
              readOnly: false
            - name: var-lib-docker
              mountPath: /var/lib/docker
              readOnly: false
            - name: tercen-tmp
              mountPath: /tmp
            - name: tercen-operator
              mountPath: /var/lib/tercen/data/operator/
              readOnly: false
            - name: tercen-renv
              mountPath: /var/lib/tercen/data/renv/
              readOnly: false

