apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tercen-worker
  labels:
    app: tercen-worker
spec:
  selector:
    matchLabels:
      name: tercen-worker
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  minReadySeconds: 60
  template:
    metadata:
      labels:
        name: tercen-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - tercen-worker
      volumes:
        - name: tercen-worker-config
          configMap:
            name: tercen-worker-config
        - name: tercen-tmp
          emptyDir: {}
        - name: var-run
          emptyDir: {}
        - name: var-lib-docker
          persistentVolumeClaim:
            claimName: tercen-var-lib-docker-pvc
#          hostPath:
#            path: /tercen/runtime/var/lib/docker
        - name: tercen-data
          persistentVolumeClaim:
            claimName: tercen-data-pvc
        - name: tercen-renv
          persistentVolumeClaim:
            claimName: tercen-renv-pvc
        - name: tercen-operator
          persistentVolumeClaim:
            claimName: tercen-operator-pvc
      containers:
        - name: tercen-worker
          image: tercen/tercen:latest
          imagePullPolicy: Always
          env:
            - name: tercen.worker.name
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: k8s.force.update
              value: "0"
            - name: tercen.worker.public.ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: tercen.worker.ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: tercen.worker.webapp.ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 5400
              name: tercen
          volumeMounts:
            - name: tercen-worker-config
              mountPath: /etc/tercen
            - name: tercen-tmp
              mountPath: /tmp
            - name: tercen-data
              mountPath: /var/lib/tercen/data
              readOnly: false
            - name: tercen-operator
              mountPath: /var/lib/tercen/data/operator/
              readOnly: false
            - name: var-run
              mountPath: /var/run/
        - name: runtime-docker
          image: docker:20.10.9-dind-alpine3.14
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: var-run
              mountPath: /var/run
              readOnly: false
            - name: var-lib-docker
              mountPath: /var/lib/docker
              readOnly: false
            - name: tercen-tmp
              mountPath: /tmp
            - name: tercen-operator
              mountPath: /var/lib/tercen/data/operator/
              readOnly: false
            - name: tercen-renv
              mountPath: /var/lib/tercen/data/renv/
              readOnly: false
#            - name: tercen-external
#              mountPath: /var/lib/tercen/external/
#              readOnly: false
        - name: runtime-r35
          image: docker:20.10
          imagePullPolicy: Always
          volumeMounts:
            - name: var-run
              mountPath: /var/run
          command: [ "sh" ]
          args: [ "-c", "docker rm -f runtime-r35 || true && docker run --rm --name runtime-r35 --network host -v /var/lib/tercen/data/operator:/var/lib/tercen/data/operator -v /var/lib/tercen/data/renv:/var/lib/tercen/data/renv -v /tmp:/tmp tercen/runtime-r35:3.5.3-6" ]
        - name: runtime-r40
          image: docker:20.10
          imagePullPolicy: Always
          volumeMounts:
            - name: var-run
              mountPath: /var/run
          command: [ "sh" ]
          args: [ "-c", "docker rm -f runtime-r40 || true && docker run --rm --name runtime-r40 --network host -v /var/lib/tercen/data/operator:/var/lib/tercen/data/operator -v /var/lib/tercen/data/renv:/var/lib/tercen/data/renv -v /tmp:/tmp tercen/runtime-r40:4.0.4-1" ]
