#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: tercen-pv
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/data/tercen"
#  storageClassName: manual
#
#---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tercen-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual

---

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: dind-pv
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/data/dind"
#  storageClassName: manual
#
#---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual